wandb_version: 1

device:
  desc: null
  value: cpu
root_dir:
  desc: null
  value: output_testing/1505
seed:
  desc: null
  value: 3
param_count:
  desc: null
  value: 5308
dataset__root:
  desc: null
  value: ../Data
dataset__name:
  desc: null
  value: simpson_wrong_2
dataset__sem_name:
  desc: null
  value: non-linear
dataset__splits:
  desc: null
  value:
  - 0.8
  - 0.1
  - 0.1
dataset__k_fold:
  desc: null
  value: 1
dataset__shuffle_train:
  desc: null
  value: true
dataset__single_split:
  desc: null
  value: false
dataset__loss:
  desc: null
  value: default
dataset__scale:
  desc: null
  value: default
dataset__num_samples:
  desc: null
  value: 50000
dataset__base_version:
  desc: null
  value: 1
dataset__add_noise:
  desc: null
  value: false
dataset__type:
  desc: null
  value: torch
dataset__use_edge_attr:
  desc: null
  value: false
dataset2__root:
  desc: null
  value: ../Data
dataset2__name:
  desc: null
  value: chain
dataset2__sem_name:
  desc: null
  value: linear
dataset2__splits:
  desc: null
  value:
  - 0.8
  - 0.2
dataset2__k_fold:
  desc: null
  value: 1
dataset2__shuffle_train:
  desc: null
  value: true
dataset2__single_split:
  desc: null
  value: false
dataset2__loss:
  desc: null
  value: default
dataset2__scale:
  desc: null
  value: default
dataset2__num_samples:
  desc: null
  value: 1000
dataset2__base_version:
  desc: null
  value: 1
dataset2__add_noise:
  desc: null
  value: false
dataset2__type:
  desc: null
  value: torch
dataset2__use_edge_attr:
  desc: null
  value: false
model__name:
  desc: null
  value: causal_nf
model__layer_name:
  desc: null
  value: nsf
model__net_name:
  desc: null
  value: mlp
model__dim_inner:
  desc: null
  value:
  - 32
  - 32
  - 32
model__num_layers:
  desc: null
  value: 1
model__init:
  desc: null
  value: null
model__act:
  desc: null
  value: elu
model__dropout:
  desc: null
  value: 0.0
model__has_bn:
  desc: null
  value: false
model__distr_u:
  desc: null
  value: laplace
model__scale_base:
  desc: null
  value: false
model__shift_base:
  desc: null
  value: false
model__scale:
  desc: null
  value: false
model__parity:
  desc: null
  value: false
model__adjacency:
  desc: null
  value: true
model__base_to_data:
  desc: null
  value: false
model__base_distr:
  desc: null
  value: normal
model__learn_base:
  desc: null
  value: false
model__plot:
  desc: null
  value: true
model__latent_dim:
  desc: null
  value: 4
model__objective:
  desc: null
  value: elbo
model__beta:
  desc: null
  value: 1.0
model__distr_x:
  desc: null
  value: normal
model__lambda_:
  desc: null
  value: 0.01
gnn__num_layers_pre:
  desc: null
  value: 1
gnn__num_layers:
  desc: null
  value: 1
gnn__num_layers_post:
  desc: null
  value: 1
gnn__dim_inner:
  desc: null
  value: 64
gnn__heads:
  desc: null
  value: 1
gnn__stage_type:
  desc: null
  value: skipsum
gnn__aggregators:
  desc: null
  value:
  - sum
  - mean
  - min
  - max
  - std
gnn__scalers:
  desc: null
  value:
  - identity
  - amplification
  - attenuation
  - linear
  - inverse_linear
gnn__towers:
  desc: null
  value: 1
gnn__pre_layers:
  desc: null
  value: 1
gnn__post_layers:
  desc: null
  value: 1
gnn__eps:
  desc: null
  value: 0.0
gnn__train_eps:
  desc: null
  value: false
gnn2__num_layers_pre:
  desc: null
  value: 1
gnn2__num_layers:
  desc: null
  value: 1
gnn2__num_layers_post:
  desc: null
  value: 1
gnn2__dim_inner:
  desc: null
  value: 64
gnn2__heads:
  desc: null
  value: 1
gnn2__stage_type:
  desc: null
  value: skipsum
gnn2__aggregators:
  desc: null
  value:
  - sum
  - mean
  - min
  - max
  - std
gnn2__scalers:
  desc: null
  value:
  - identity
  - amplification
  - attenuation
  - linear
  - inverse_linear
gnn2__towers:
  desc: null
  value: 1
gnn2__pre_layers:
  desc: null
  value: 1
gnn2__post_layers:
  desc: null
  value: 1
gnn2__eps:
  desc: null
  value: 0.0
gnn2__train_eps:
  desc: null
  value: false
train__regularize:
  desc: null
  value: false
train__kl:
  desc: null
  value: forward
train__max_epochs:
  desc: null
  value: 1000
train__batch_size:
  desc: null
  value: 4096
train__num_workers:
  desc: null
  value: 0
train__limit_train_batches:
  desc: null
  value: null
train__limit_val_batches:
  desc: null
  value: null
train__auto_scale_batch_size:
  desc: null
  value: false
train__auto_lr_find:
  desc: null
  value: false
train__profiler:
  desc: null
  value: null
train__enable_progress_bar:
  desc: null
  value: true
train__max_time:
  desc: null
  value: 00:01:00:00
train__model_checkpoint:
  desc: null
  value: true
train__inference_mode:
  desc: null
  value: false
early_stopping__activate:
  desc: null
  value: false
early_stopping__min_delta:
  desc: null
  value: 0.0
early_stopping__patience:
  desc: null
  value: 3
early_stopping__verbose:
  desc: null
  value: false
optim__optimizer:
  desc: null
  value: adam
optim__base_lr:
  desc: null
  value: 0.001
optim__beta_1:
  desc: null
  value: 0.9
optim__beta_2:
  desc: null
  value: 0.999
optim__momentum:
  desc: null
  value: 0.0
optim__weight_decay:
  desc: null
  value: 0.0
optim__scheduler:
  desc: null
  value: plateau
optim__gamma:
  desc: null
  value: 0.99
optim__step_size:
  desc: null
  value: 100
optim__mode:
  desc: null
  value: min
optim__factor:
  desc: null
  value: 0.95
optim__patience:
  desc: null
  value: 60
optim__cooldown:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.15.8
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716650945.161864
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 77
      2:
      - 1
      - 9
      - 41
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.10.7
      5: 0.15.8
      8:
      - 4
      - 5
