device: cpu
root_dir: output_testing/1505
seed: 3
dataset:
  root: ../Data
  name: simpson
  sem_name: non-linear  #non-linear # non-linear #non-additive
  splits: [ 1.0, 0, 0 ]
  k_fold: 1
  shuffle_train: True
  loss: default
  scale: default 
  num_samples: 50000
  base_version: 1
dataset2:
  root: ../Data
  name: simpson_wrong_2
  sem_name: non-linear    # non-linear #non-additive
  splits: [ 1.0, 0, 0 ]
  k_fold: 1
  shuffle_train: True
  loss: default
  scale: default
  num_samples: 50000
  base_version: 1
model:
  name: causal_nf
  layer_name: nsf
  dim_inner: [32, 32, 32]
  num_layers: 1
  init: None
  act: elu
  adjacency: True
  base_to_data: False
  base_distr: normal
  learn_base: False
  plot: True
